/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package interfazUsuario;

import control.Tabla;
import java.awt.Dimension;
import java.awt.Toolkit;
import control.Control;

/**
 *
 * @author EquipoSiete
 */
public class FrmAbarrotes extends javax.swing.JFrame {
    private javax.swing.JTable tabla;
    Control control = new Control(); 

    /**
     * Constructor de la ventana principal.
     */
    public FrmAbarrotes() {
        initComponents();
        centrarVentana();
    }
    
    /** 
     * Este método centra la ventana de la aplicación sobre la pantalla
     */
    public void centrarVentana(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        
        setLocation((screenSize.width-frameSize.width)/2, (screenSize.height-frameSize.height)/2);
    }
    
     /**
     * Este método crea un objeto del tipo JTable dentro de un panel con barras
     * de deslizamiento y la despliega
     * @param tabla objeto TableModel con los datos de una tabla
     */
    public void despliegaTabla(Tabla tabla){

        // Crea la tabla a partir del modelo de la tabla con los valores
        // de los titulos de las columnas y los valores de las celdas
        jtabla = new javax.swing.JTable(tabla.getModeloTabla());
        
        // Establece el título de la tabla
        tituloTabla.setText(tabla.getTitulo());
        
        // Hace que el control del tamaño de la tabla y la porción visible
        // lo tenga la barra de deslizamiento y no la tabla
        jtabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtabla.setAutoscrolls(false);
        
        // Hace visible la tabla dentro del panel con barras de
        // deslizamiento
        jScrollPane1.setViewportView(jtabla);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        tituloTabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuBar = new javax.swing.JMenuBar();
        menuCatalogo = new javax.swing.JMenu();
        menuCatalogoProductos = new javax.swing.JMenu();
        opcionMenuAgregarProducto = new javax.swing.JMenuItem();
        opcionMenuActualizarProducto = new javax.swing.JMenuItem();
        opcionMenuEliminarProducto = new javax.swing.JMenuItem();
        Separador1 = new javax.swing.JPopupMenu.Separator();
        opcionMenuSalir = new javax.swing.JMenuItem();
        menuInventarios = new javax.swing.JMenu();
        menuInventarioEmpacados = new javax.swing.JMenu();
        opcionMenuActualizarInventarioEmpacadosCompras = new javax.swing.JMenuItem();
        pcionMenuActualizarInventarioEmpacadosVentas = new javax.swing.JMenuItem();
        menuInventarioGranel = new javax.swing.JMenu();
        opcionMenuActualizarInventarioGranelCompras = new javax.swing.JMenuItem();
        opcionMenuActualizarInventarioGranelVentas = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        menuComprasEmpacados = new javax.swing.JMenu();
        opcionMenuAgregarCompraEmpacados = new javax.swing.JMenuItem();
        opcionMenuActualizarCompraEmpacados = new javax.swing.JMenuItem();
        opcionMenuEliminarCompraEmpacados = new javax.swing.JMenuItem();
        menuVentasEmpacados = new javax.swing.JMenu();
        opcionMenuAgregarVentaEmpacados = new javax.swing.JMenuItem();
        opcionMenuActualizarVentaEmpacados = new javax.swing.JMenuItem();
        opcionMenuEliminarVentaEmpacados = new javax.swing.JMenuItem();
        menuComprasGranel = new javax.swing.JMenu();
        opcionMenuAgregarCompraGranel = new javax.swing.JMenuItem();
        opcionMenuActualizarCompraGranel = new javax.swing.JMenuItem();
        opcionMenuEliminarCompraGranel = new javax.swing.JMenuItem();
        menuVentasGranel = new javax.swing.JMenu();
        opcionMenuAgregarVentaGranel = new javax.swing.JMenuItem();
        opcionMenuActualizarVentaGranel = new javax.swing.JMenuItem();
        opcionMenuEliminarVentaGranel = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsultaProductos = new javax.swing.JMenu();
        opcionMenuConsultaProductos = new javax.swing.JMenuItem();
        opcionMenuConsultaProductosEmpacados = new javax.swing.JMenuItem();
        opcionMenuConsultaProductosGranel = new javax.swing.JMenuItem();
        menuConsultaInventarios = new javax.swing.JMenu();
        opcionMenuConsultaInventarioEmpacados = new javax.swing.JMenuItem();
        opcionMenuConsultaInventarioGranel = new javax.swing.JMenuItem();
        menuConsultaComprasEmpacado = new javax.swing.JMenu();
        opcionMenuConsultaComprasEmpacados = new javax.swing.JMenuItem();
        opcionMenuConsultaComprasEmpacadosPeriodo = new javax.swing.JMenuItem();
        menuConsultaVentasEmpacado = new javax.swing.JMenu();
        opcionMenuConsultaVentasEmpacados = new javax.swing.JMenuItem();
        opcionMenuConsultaVentasEmpacadosPeriodo = new javax.swing.JMenuItem();
        menuConsultaComprasGranel = new javax.swing.JMenu();
        opcionMenuConsultaComprasGranel = new javax.swing.JMenuItem();
        opcionMenuConsultaComprasGranelPeriodo = new javax.swing.JMenuItem();
        menuConsultaVentasGranel = new javax.swing.JMenu();
        opcionMenuConsultaVentasGranel = new javax.swing.JMenuItem();
        opcionMenuConsultaVentasGranelPeriodo = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        opcionMenuAcercaDe = new javax.swing.JMenuItem();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Abarrotes");

        tituloTabla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));

        menuCatalogo.setMnemonic('f');
        menuCatalogo.setText("Catalogos");

        menuCatalogoProductos.setText("Productos");

        opcionMenuAgregarProducto.setText("Agregar");
        opcionMenuAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarProductoActionPerformed(evt);
            }
        });
        menuCatalogoProductos.add(opcionMenuAgregarProducto);

        opcionMenuActualizarProducto.setText("Actualizar");
        opcionMenuActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizarProductoActionPerformed(evt);
            }
        });
        menuCatalogoProductos.add(opcionMenuActualizarProducto);

        opcionMenuEliminarProducto.setText("Eliminar");
        opcionMenuEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuEliminarProductoActionPerformed(evt);
            }
        });
        menuCatalogoProductos.add(opcionMenuEliminarProducto);

        menuCatalogo.add(menuCatalogoProductos);
        menuCatalogo.add(Separador1);

        opcionMenuSalir.setMnemonic('x');
        opcionMenuSalir.setText("Salir");
        opcionMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuSalirActionPerformed(evt);
            }
        });
        menuCatalogo.add(opcionMenuSalir);

        menuBar.add(menuCatalogo);

        menuInventarios.setMnemonic('e');
        menuInventarios.setText("Inventarios");

        menuInventarioEmpacados.setText("Productos Empacados");

        opcionMenuActualizarInventarioEmpacadosCompras.setText("Actualizar con compras");
        opcionMenuActualizarInventarioEmpacadosCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizarInventarioEmpacadosComprasActionPerformed(evt);
            }
        });
        menuInventarioEmpacados.add(opcionMenuActualizarInventarioEmpacadosCompras);

        pcionMenuActualizarInventarioEmpacadosVentas.setText("Actualizar con ventas");
        pcionMenuActualizarInventarioEmpacadosVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcionMenuActualizarInventarioEmpacadosVentasActionPerformed(evt);
            }
        });
        menuInventarioEmpacados.add(pcionMenuActualizarInventarioEmpacadosVentas);

        menuInventarios.add(menuInventarioEmpacados);

        menuInventarioGranel.setText("Productos Granel");

        opcionMenuActualizarInventarioGranelCompras.setText("Actualizar con compras");
        opcionMenuActualizarInventarioGranelCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizarInventarioGranelComprasActionPerformed(evt);
            }
        });
        menuInventarioGranel.add(opcionMenuActualizarInventarioGranelCompras);

        opcionMenuActualizarInventarioGranelVentas.setText("Actualizar con ventas");
        opcionMenuActualizarInventarioGranelVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizarInventarioGranelVentasActionPerformed(evt);
            }
        });
        menuInventarioGranel.add(opcionMenuActualizarInventarioGranelVentas);

        menuInventarios.add(menuInventarioGranel);

        menuBar.add(menuInventarios);

        menuMovimientos.setMnemonic('h');
        menuMovimientos.setText("Movimientos");

        menuComprasEmpacados.setText("Compra Productos Empacados");

        opcionMenuAgregarCompraEmpacados.setText("Agregar");
        opcionMenuAgregarCompraEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarCompraEmpacadosActionPerformed(evt);
            }
        });
        menuComprasEmpacados.add(opcionMenuAgregarCompraEmpacados);

        opcionMenuActualizarCompraEmpacados.setText("Actualizar");
        opcionMenuActualizarCompraEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizarCompraEmpacadosActionPerformed(evt);
            }
        });
        menuComprasEmpacados.add(opcionMenuActualizarCompraEmpacados);

        opcionMenuEliminarCompraEmpacados.setText("Eliminar");
        opcionMenuEliminarCompraEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuEliminarCompraEmpacadosActionPerformed(evt);
            }
        });
        menuComprasEmpacados.add(opcionMenuEliminarCompraEmpacados);

        menuMovimientos.add(menuComprasEmpacados);

        menuVentasEmpacados.setText("Venta Productos Empacados");

        opcionMenuAgregarVentaEmpacados.setText("Agregar");
        opcionMenuAgregarVentaEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarVentaEmpacadosActionPerformed(evt);
            }
        });
        menuVentasEmpacados.add(opcionMenuAgregarVentaEmpacados);

        opcionMenuActualizarVentaEmpacados.setText("Actualizar");
        opcionMenuActualizarVentaEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizarVentaEmpacadosActionPerformed(evt);
            }
        });
        menuVentasEmpacados.add(opcionMenuActualizarVentaEmpacados);

        opcionMenuEliminarVentaEmpacados.setText("Eliminar");
        opcionMenuEliminarVentaEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuEliminarVentaEmpacadosActionPerformed(evt);
            }
        });
        menuVentasEmpacados.add(opcionMenuEliminarVentaEmpacados);

        menuMovimientos.add(menuVentasEmpacados);

        menuComprasGranel.setText("Compra Productos Granel");

        opcionMenuAgregarCompraGranel.setText("Agregar");
        opcionMenuAgregarCompraGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarCompraGranelActionPerformed(evt);
            }
        });
        menuComprasGranel.add(opcionMenuAgregarCompraGranel);

        opcionMenuActualizarCompraGranel.setText("Actualizar");
        opcionMenuActualizarCompraGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizarCompraGranelActionPerformed(evt);
            }
        });
        menuComprasGranel.add(opcionMenuActualizarCompraGranel);

        opcionMenuEliminarCompraGranel.setText("Eliminar");
        opcionMenuEliminarCompraGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuEliminarCompraGranelActionPerformed(evt);
            }
        });
        menuComprasGranel.add(opcionMenuEliminarCompraGranel);

        menuMovimientos.add(menuComprasGranel);

        menuVentasGranel.setText("Venta Productos Granel");

        opcionMenuAgregarVentaGranel.setText("Agregar");
        opcionMenuAgregarVentaGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAgregarVentaGranelActionPerformed(evt);
            }
        });
        menuVentasGranel.add(opcionMenuAgregarVentaGranel);

        opcionMenuActualizarVentaGranel.setText("Actualizar");
        opcionMenuActualizarVentaGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuActualizarVentaGranelActionPerformed(evt);
            }
        });
        menuVentasGranel.add(opcionMenuActualizarVentaGranel);

        opcionMenuEliminarVentaGranel.setText("Eliminar");
        opcionMenuEliminarVentaGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuEliminarVentaGranelActionPerformed(evt);
            }
        });
        menuVentasGranel.add(opcionMenuEliminarVentaGranel);

        menuMovimientos.add(menuVentasGranel);

        menuBar.add(menuMovimientos);

        menuConsultas.setText("Consultas");

        menuConsultaProductos.setText("Productos");

        opcionMenuConsultaProductos.setText("Todos");
        opcionMenuConsultaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaProductosActionPerformed(evt);
            }
        });
        menuConsultaProductos.add(opcionMenuConsultaProductos);

        opcionMenuConsultaProductosEmpacados.setText("Empacados");
        opcionMenuConsultaProductosEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaProductosEmpacadosActionPerformed(evt);
            }
        });
        menuConsultaProductos.add(opcionMenuConsultaProductosEmpacados);

        opcionMenuConsultaProductosGranel.setText("Granel");
        opcionMenuConsultaProductosGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaProductosGranelActionPerformed(evt);
            }
        });
        menuConsultaProductos.add(opcionMenuConsultaProductosGranel);

        menuConsultas.add(menuConsultaProductos);

        menuConsultaInventarios.setText("Inventarios");

        opcionMenuConsultaInventarioEmpacados.setText("Productos Empacados");
        opcionMenuConsultaInventarioEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaInventarioEmpacadosActionPerformed(evt);
            }
        });
        menuConsultaInventarios.add(opcionMenuConsultaInventarioEmpacados);

        opcionMenuConsultaInventarioGranel.setText("Productos Granel");
        opcionMenuConsultaInventarioGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaInventarioGranelActionPerformed(evt);
            }
        });
        menuConsultaInventarios.add(opcionMenuConsultaInventarioGranel);

        menuConsultas.add(menuConsultaInventarios);

        menuConsultaComprasEmpacado.setText("Compra Productos Empacados");

        opcionMenuConsultaComprasEmpacados.setText("Todas");
        opcionMenuConsultaComprasEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaComprasEmpacadosActionPerformed(evt);
            }
        });
        menuConsultaComprasEmpacado.add(opcionMenuConsultaComprasEmpacados);

        opcionMenuConsultaComprasEmpacadosPeriodo.setText("Por Periodo");
        opcionMenuConsultaComprasEmpacadosPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaComprasEmpacadosPeriodoActionPerformed(evt);
            }
        });
        menuConsultaComprasEmpacado.add(opcionMenuConsultaComprasEmpacadosPeriodo);

        menuConsultas.add(menuConsultaComprasEmpacado);

        menuConsultaVentasEmpacado.setText("Venta Productos Empacados");

        opcionMenuConsultaVentasEmpacados.setText("Todas");
        opcionMenuConsultaVentasEmpacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaVentasEmpacadosActionPerformed(evt);
            }
        });
        menuConsultaVentasEmpacado.add(opcionMenuConsultaVentasEmpacados);

        opcionMenuConsultaVentasEmpacadosPeriodo.setText("Por Periodo");
        opcionMenuConsultaVentasEmpacadosPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaVentasEmpacadosPeriodoActionPerformed(evt);
            }
        });
        menuConsultaVentasEmpacado.add(opcionMenuConsultaVentasEmpacadosPeriodo);

        menuConsultas.add(menuConsultaVentasEmpacado);

        menuConsultaComprasGranel.setText("Compra Productos Granel");

        opcionMenuConsultaComprasGranel.setText("Todas");
        opcionMenuConsultaComprasGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaComprasGranelActionPerformed(evt);
            }
        });
        menuConsultaComprasGranel.add(opcionMenuConsultaComprasGranel);

        opcionMenuConsultaComprasGranelPeriodo.setText("Por Periodo");
        opcionMenuConsultaComprasGranelPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaComprasGranelPeriodoActionPerformed(evt);
            }
        });
        menuConsultaComprasGranel.add(opcionMenuConsultaComprasGranelPeriodo);

        menuConsultas.add(menuConsultaComprasGranel);

        menuConsultaVentasGranel.setText("Venta Productos Granel");

        opcionMenuConsultaVentasGranel.setText("Todas");
        opcionMenuConsultaVentasGranel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaVentasGranelActionPerformed(evt);
            }
        });
        menuConsultaVentasGranel.add(opcionMenuConsultaVentasGranel);

        opcionMenuConsultaVentasGranelPeriodo.setText("Por Periodo");
        opcionMenuConsultaVentasGranelPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuConsultaVentasGranelPeriodoActionPerformed(evt);
            }
        });
        menuConsultaVentasGranel.add(opcionMenuConsultaVentasGranelPeriodo);

        menuConsultas.add(menuConsultaVentasGranel);

        menuBar.add(menuConsultas);

        menuAyuda.setText("Ayuda");

        opcionMenuAcercaDe.setText("Acerca de");
        opcionMenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(opcionMenuAcercaDe);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(tituloTabla))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(tituloTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** 
     * Metodo oyente de la opcion salir, sale de la ventana.
     * @param evt evento al que escuchara.
     */
    private void opcionMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opcionMenuSalirActionPerformed

    /** 
     * Método oyente que llama desde la clase control al método eliminarProducto.
     * Esté método tambien despliega una tabla de los productos con
     * los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuEliminarProductoActionPerformed
        control.eliminarProducto(this);
        Tabla tablaProductos = control.getTablaProductos(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuEliminarProductoActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizarInventarioVentasEmapacado.
     * Esté método tambien despliega una tabla del inventario con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void pcionMenuActualizarInventarioEmpacadosVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcionMenuActualizarInventarioEmpacadosVentasActionPerformed
        control.actualizarInventarioVentasEmapacado(this);
        Tabla tablaProductos = control.getTablaInventarioProductosEmpacados(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_pcionMenuActualizarInventarioEmpacadosVentasActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizarInventarioVentasGranel.
     * Esté método tambien despliega una tabla del inventario con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuActualizarInventarioGranelVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizarInventarioGranelVentasActionPerformed
        control.actualizarInventarioVentasGranel(this);
        Tabla tablaProductos = control.getTablaInventarioProductosGranel(this);
        if (tablaProductos!= null) {
        despliegaTabla(tablaProductos);    
        }
        
    }//GEN-LAST:event_opcionMenuActualizarInventarioGranelVentasActionPerformed
    /**
     * Método oyente que llama desde la clase control al método eliminarCompraEmpacado.
     * Esté método tambien despliega una tabla de las compras Empacado con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuEliminarCompraEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuEliminarCompraEmpacadosActionPerformed
        control.eliminarCompraEmpacado(this);
        Tabla tablaProductos = control.getTablaComprasProductosEmpacados(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuEliminarCompraEmpacadosActionPerformed
    /**
     * Método oyente que llama desde la clase control al método eliminarVentaEmpacado.
     * Esté método tambien despliega una tabla de las ventas Empacado con los cambios hechos.
     * 
     * @param evt 
     */
    private void opcionMenuEliminarVentaEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuEliminarVentaEmpacadosActionPerformed
        control.eliminarVentaEmpacado(this);
        Tabla tablaProductos = control.getTablaVentasProductosEmpacados(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuEliminarVentaEmpacadosActionPerformed
    /**
     * Método oyente que llama desde la clase control al método eliminarCompraGranel.
     * Esté método tambien despliega una tabla de las compras Granel con los cambios hechos.
     * 
     * @param evt 
     */
    private void opcionMenuEliminarCompraGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuEliminarCompraGranelActionPerformed
        control.eliminarCompraGranel(this);
        Tabla tablaProductos = control.getTablaComprasProductosGranel(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuEliminarCompraGranelActionPerformed
    /**
     * Método oyente que llama desde la clase control al método eliminarVentaGranel.
     * Esté método tambien despliega una tabla de las ventas Granel con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuEliminarVentaGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuEliminarVentaGranelActionPerformed
       control.eliminarVentaGranel(this);
        Tabla tablaProductos = control.getTablaVentasProductosGranel(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuEliminarVentaGranelActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Productos)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaProductosActionPerformed
        Tabla tablaProductos = control.getTablaProductos2(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaProductosActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Productos Granel)
     * 
     * @param evt 
     */
    private void opcionMenuConsultaProductosGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaProductosGranelActionPerformed
        Tabla tablaProductos;
        tablaProductos = control.getTablaProductosGranel2(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaProductosGranelActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Compras Empacado)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaComprasEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaComprasEmpacadosActionPerformed
        Tabla tablaProductos;
        tablaProductos = control.getTablaComprasProductosEmpacados2(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaComprasEmpacadosActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará.(Ventas Empacado)
     * 
     * @param evt 
     */
    private void opcionMenuConsultaVentasEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaVentasEmpacadosActionPerformed
        Tabla tablaProductos;
        tablaProductos = control.getTablaVentasProductosEmpacados2(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaVentasEmpacadosActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Compras Granel)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaComprasGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaComprasGranelActionPerformed
        Tabla tablaProductos;
        tablaProductos = control.getTablaComprasProductosGranel2(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaComprasGranelActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Ventas Granel)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaVentasGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaVentasGranelActionPerformed
        Tabla tablaProductos;
        tablaProductos = control.getTablaVentasProductosGranel2(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaVentasGranelActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Inventario Empacados)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaInventarioEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaInventarioEmpacadosActionPerformed
        Tabla tablaProductos;
        tablaProductos = control.getTablaInventarioProductosEmpacados2(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaInventarioEmpacadosActionPerformed
    /**
     * Método oyente que llama desde la clase control al método agregarProducto.
     * Esté método tambien despliega una tabla de los productos con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarProductoActionPerformed
        control.agregarProducto(this);
        Tabla tablaProductos = control.getTablaProductos(this);
        if  (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuAgregarProductoActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizaProducto.
     * Esté método tambien despliega una tabla de los productos con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizarProductoActionPerformed
        control.actualizaProducto(this);
        Tabla tablaProductos = control.getTablaProductos(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuActualizarProductoActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizarInventarioComprasEmpacado.
     * Esté método tambien despliega una tabla del inventario de compras empacado con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuActualizarInventarioEmpacadosComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizarInventarioEmpacadosComprasActionPerformed
        control.actualizarInventarioComprasEmpacado(this);
        Tabla tablaProductos = control.getTablaInventarioProductosGranel(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuActualizarInventarioEmpacadosComprasActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizarInventarioComprasGranel .
     * Esté método tambien despliega una tabla del inventario de compras granel con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuActualizarInventarioGranelComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizarInventarioGranelComprasActionPerformed
        control.actualizarInventarioComprasGranel(this);
        Tabla tablaProductos = control.getTablaInventarioProductosGranel(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuActualizarInventarioGranelComprasActionPerformed
    /**
     * Método oyente que llama desde la clase control al método agregarCompraEmpacado.
     * Esté método tambien despliega una tabla de las compras empacados con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuAgregarCompraEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarCompraEmpacadosActionPerformed
        control.agregarCompraEmpacado(this);
        Tabla tablaProductos = control.getTablaComprasProductosEmpacados(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuAgregarCompraEmpacadosActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizarCompraEmpacado.
     * Esté método tambien despliega una tabla de las compras productos empacados con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuActualizarCompraEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizarCompraEmpacadosActionPerformed
        control.actualizarCompraEmpacado(this);
        Tabla tablaProductos = control.getTablaComprasProductosEmpacados(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuActualizarCompraEmpacadosActionPerformed
    /**
     * Método oyente que llama desde la clase control al método agregarVentaEmpacado.
     * Esté método tambien despliega una tabla de las ventas productos empacados con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuAgregarVentaEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarVentaEmpacadosActionPerformed
        control.agregarVentaEmpacado(this);
        Tabla tablaProductos = control.getTablaVentasProductosEmpacados(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuAgregarVentaEmpacadosActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizarVentaEmpacado.
     * Esté método tambien despliega una tabla de las ventas productos empacados con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuActualizarVentaEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizarVentaEmpacadosActionPerformed
        control.actualizarVentaEmpacado(this);
        Tabla tablaProductos = control.getTablaVentasProductosEmpacados(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuActualizarVentaEmpacadosActionPerformed
    /**
     * Método oyente que llama desde la clase control al método agregarCompraGranel.
     * Esté método tambien despliega una tabla de las compras productos granel con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuAgregarCompraGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarCompraGranelActionPerformed
        control.agregarCompraGranel(this);
        Tabla tablaProductos = control.getTablaComprasProductosGranel(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuAgregarCompraGranelActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizarCompraGranel.
     * Esté método tambien despliega una tabla de las compras productos granel con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuActualizarCompraGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizarCompraGranelActionPerformed
        control.actualizarCompraGranel(this);
        Tabla tablaProductos = control.getTablaComprasProductosGranel(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuActualizarCompraGranelActionPerformed
    /**
     * Método oyente que llama desde la clase control al método agregarVentaGranel.
     * Esté método tambien despliega una tabla de las ventas productos granel con los cambios hechos.
     * 
     * @param evt Evento. 
     */
    private void opcionMenuAgregarVentaGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAgregarVentaGranelActionPerformed
        control.agregarVentaGranel(this);
        Tabla tablaProductos = control.getTablaVentasProductosGranel(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuAgregarVentaGranelActionPerformed
    /**
     * Método oyente que llama desde la clase control al método actualizarVentaGranel.
     * Esté método tambien despliega una tabla de las ventas productos granel con los cambios hechos.
     * 
     * @param evt Evento.
     */
    private void opcionMenuActualizarVentaGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuActualizarVentaGranelActionPerformed
        control.actualizarVentaGranel(this);
        Tabla tablaProductos = control.getTablaVentasProductosGranel(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuActualizarVentaGranelActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Productos Empacados)
     *
     * @param evt Evento.
     */
    private void opcionMenuConsultaProductosEmpacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaProductosEmpacadosActionPerformed
        Tabla tablaProductos = control.getTablaProductosEmpacados2(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaProductosEmpacadosActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Inventario Granel)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaInventarioGranelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaInventarioGranelActionPerformed
        Tabla tablaProductos;
        tablaProductos = control.getTablaInventarioProductosGranel2(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaInventarioGranelActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Compras Empacado Periodo)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaComprasEmpacadosPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaComprasEmpacadosPeriodoActionPerformed
        Tabla tablaProductos = control.getTablaComprasProductosEmpacadosPeriodo(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaComprasEmpacadosPeriodoActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Ventas Empacado Periodo)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaVentasEmpacadosPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaVentasEmpacadosPeriodoActionPerformed
        Tabla tablaProductos = control.getTablaVentasProductosEmpacadosPeriodo(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaVentasEmpacadosPeriodoActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Compras Granel Periodo)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaComprasGranelPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaComprasGranelPeriodoActionPerformed
       Tabla tablaProductos = control.getTablaComprasProductosGranelPeriodo(this);
        if (tablaProductos!=null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaComprasGranelPeriodoActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un objeto de tipo Tabla, y le asigna 
     * con ayuda de un método de la clase control que obtiene una tabla y al final
     * la mostrará. (Ventas Granel Periodo)
     * 
     * @param evt Evento.
     */
    private void opcionMenuConsultaVentasGranelPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuConsultaVentasGranelPeriodoActionPerformed
        Tabla tablaProductos = control.getTablaVentasProductosGranelPeriodo(this);
        if (tablaProductos != null) {
            despliegaTabla(tablaProductos);
        }
    }//GEN-LAST:event_opcionMenuConsultaVentasGranelPeriodoActionPerformed
    /**
     * Método oyente que al ocurrir el evento crea un nuevo frame, con información
     * de los guapos y talentosos programadores.
     * 
     * @param evt Evento.
     */
    private void opcionMenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAcercaDeActionPerformed
        DlgAcercaDe dlg = new DlgAcercaDe(this, "Acerca de", true);
        dlg.setVisible(true);
        //        JOptionPane.showMessageDialog(this, "Jesus Rene Gonzalez Castro 00000247336\n Enrique Rodríguez Angulo 00000246966", "Acerca de:", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_opcionMenuAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAbarrotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAbarrotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator Separador1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCatalogo;
    private javax.swing.JMenu menuCatalogoProductos;
    private javax.swing.JMenu menuComprasEmpacados;
    private javax.swing.JMenu menuComprasGranel;
    private javax.swing.JMenu menuConsultaComprasEmpacado;
    private javax.swing.JMenu menuConsultaComprasGranel;
    private javax.swing.JMenu menuConsultaInventarios;
    private javax.swing.JMenu menuConsultaProductos;
    private javax.swing.JMenu menuConsultaVentasEmpacado;
    private javax.swing.JMenu menuConsultaVentasGranel;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuInventarioEmpacados;
    private javax.swing.JMenu menuInventarioGranel;
    private javax.swing.JMenu menuInventarios;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuVentasEmpacados;
    private javax.swing.JMenu menuVentasGranel;
    private javax.swing.JMenuItem opcionMenuAcercaDe;
    private javax.swing.JMenuItem opcionMenuActualizarCompraEmpacados;
    private javax.swing.JMenuItem opcionMenuActualizarCompraGranel;
    private javax.swing.JMenuItem opcionMenuActualizarInventarioEmpacadosCompras;
    private javax.swing.JMenuItem opcionMenuActualizarInventarioGranelCompras;
    private javax.swing.JMenuItem opcionMenuActualizarInventarioGranelVentas;
    private javax.swing.JMenuItem opcionMenuActualizarProducto;
    private javax.swing.JMenuItem opcionMenuActualizarVentaEmpacados;
    private javax.swing.JMenuItem opcionMenuActualizarVentaGranel;
    private javax.swing.JMenuItem opcionMenuAgregarCompraEmpacados;
    private javax.swing.JMenuItem opcionMenuAgregarCompraGranel;
    private javax.swing.JMenuItem opcionMenuAgregarProducto;
    private javax.swing.JMenuItem opcionMenuAgregarVentaEmpacados;
    private javax.swing.JMenuItem opcionMenuAgregarVentaGranel;
    private javax.swing.JMenuItem opcionMenuConsultaComprasEmpacados;
    private javax.swing.JMenuItem opcionMenuConsultaComprasEmpacadosPeriodo;
    private javax.swing.JMenuItem opcionMenuConsultaComprasGranel;
    private javax.swing.JMenuItem opcionMenuConsultaComprasGranelPeriodo;
    private javax.swing.JMenuItem opcionMenuConsultaInventarioEmpacados;
    private javax.swing.JMenuItem opcionMenuConsultaInventarioGranel;
    private javax.swing.JMenuItem opcionMenuConsultaProductos;
    private javax.swing.JMenuItem opcionMenuConsultaProductosEmpacados;
    private javax.swing.JMenuItem opcionMenuConsultaProductosGranel;
    private javax.swing.JMenuItem opcionMenuConsultaVentasEmpacados;
    private javax.swing.JMenuItem opcionMenuConsultaVentasEmpacadosPeriodo;
    private javax.swing.JMenuItem opcionMenuConsultaVentasGranel;
    private javax.swing.JMenuItem opcionMenuConsultaVentasGranelPeriodo;
    private javax.swing.JMenuItem opcionMenuEliminarCompraEmpacados;
    private javax.swing.JMenuItem opcionMenuEliminarCompraGranel;
    private javax.swing.JMenuItem opcionMenuEliminarProducto;
    private javax.swing.JMenuItem opcionMenuEliminarVentaEmpacados;
    private javax.swing.JMenuItem opcionMenuEliminarVentaGranel;
    private javax.swing.JMenuItem opcionMenuSalir;
    private javax.swing.JMenuItem pcionMenuActualizarInventarioEmpacadosVentas;
    private javax.swing.JLabel tituloTabla;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTable jtabla;
}
