
package interfazUsuario;

import javax.swing.JOptionPane;

/**
 *
 * @author Nomar Limon
 */
public class Registro extends javax.swing.JDialog {

    public StringBuffer respuesta;
    
    /**
     * Creates new form Registro
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.respuesta = new StringBuffer();
    }
    
   private boolean validarEntrada(String usuario, String email, char[] contraseña, String telefono) {
       /*
        JOptionPane.showMessageDialog(
                this,
                "La contrasena no debe contener espacios ni simbolos y ser de 8 a 30 caracteres como maximo",
                "Contraseña Erronea",
                JOptionPane.ERROR_MESSAGE
            );
       */
       /*
       
    // Validación de longitud mínima y máxima
    if (usuario.length() < 10 || usuario.length() > 100 ||
        email.length() < 10 || email.length() > 100 ||
        contraseña.length < 10 || contraseña.length > 100 ||
        telefono.length() < 10 || telefono.length() > 100) {
        JOptionPane.showMessageDialog(this, "Longitud inválida. El usuario, email, contraseña y teléfono deben tener entre 10 y 100 caracteres.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validación de caracteres alfanuméricos
    if (!usuario.matches("^[a-zA-Z0-9]*$")) {
        JOptionPane.showMessageDialog(this, "El usuario solo puede contener caracteres alfanuméricos.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validación de formato de email
    if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
        JOptionPane.showMessageDialog(this, "Formato de email inválido.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validación de números en el campo de teléfono
    if (!telefono.matches("^[0-9]+$")) {
        JOptionPane.showMessageDialog(this, "El campo de teléfono solo puede contener números.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validación de no nulos
    if (usuario.isEmpty() || email.isEmpty() || contraseña.length == 0 || telefono.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ninguno de los campos puede estar vacío.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;  // Todas las validaciones fueron exitosas
    */
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsuarioRegistro = new javax.swing.JLabel();
        labelEmailRegistro = new javax.swing.JLabel();
        labelContraseñaRegistro = new javax.swing.JLabel();
        botonRegistrarUsuario = new javax.swing.JButton();
        campoTextoNombreUsuario = new javax.swing.JTextField();
        campoTextoEmailUsuario = new javax.swing.JTextField();
        campoContrasenaUsuario = new javax.swing.JPasswordField();
        labelTelefono = new javax.swing.JLabel();
        campoTextoTelefonoUsuario = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        cajaCombinadaRolUsuario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Usuario");

        labelUsuarioRegistro.setText("Nombre:");

        labelEmailRegistro.setText("Correo electronico:");

        labelContraseñaRegistro.setText("Contraseña:");

        botonRegistrarUsuario.setText("Registrar usuario");
        botonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarUsuarioActionPerformed(evt);
            }
        });

        campoTextoNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNombreUsuarioActionPerformed(evt);
            }
        });

        campoTextoEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEmailUsuarioActionPerformed(evt);
            }
        });

        campoContrasenaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContrasenaUsuarioActionPerformed(evt);
            }
        });

        labelTelefono.setText("Telefono:");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        cajaCombinadaRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Repartidor" }));

        jLabel1.setText("Rol de usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRegistrarUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmailRegistro)
                            .addComponent(labelTelefono)
                            .addComponent(jLabel1)
                            .addComponent(labelContraseñaRegistro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cajaCombinadaRolUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoTextoTelefonoUsuario)
                                .addComponent(campoTextoEmailUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(campoContrasenaUsuario))
                            .addComponent(campoTextoNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuarioRegistro)
                    .addComponent(campoTextoNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEmailRegistro)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(campoTextoEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono)
                    .addComponent(campoTextoTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoContrasenaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContraseñaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaCombinadaRolUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrarUsuario)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarUsuarioActionPerformed
        
    }//GEN-LAST:event_botonRegistrarUsuarioActionPerformed

    private void campoTextoNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNombreUsuarioActionPerformed

    private void campoTextoEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEmailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoEmailUsuarioActionPerformed

    private void campoContrasenaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContrasenaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContrasenaUsuarioActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrarUsuario;
    private javax.swing.JComboBox<String> cajaCombinadaRolUsuario;
    private javax.swing.JPasswordField campoContrasenaUsuario;
    private javax.swing.JTextField campoTextoEmailUsuario;
    private javax.swing.JTextField campoTextoNombreUsuario;
    private javax.swing.JTextField campoTextoTelefonoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelContraseñaRegistro;
    private javax.swing.JLabel labelEmailRegistro;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
